root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/processor"
  cmd = "go build -buildvcs=false -o ./tmp/processor ./processor/cmd"
  delay = 100
  exclude_dir = ["tmp", "vendor", "testdata", "uploads", "outputs", "temp", "bin", ".git", "docs", "node_modules", "cypress", ".github", ".vscode", ".idea", "web/node_modules", "web/cypress", "web/coverage", "coverage"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors-processor.log"
  poll = true
  poll_interval = 500
  rerun = false
  rerun_delay = 1000
  send_interrupt = true
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
